lucidworks/spark-solr

pom.xml
src/main/scala/com/lucidworks/spark/SolrScalaRDD.scala
src/main/scala/com/lucidworks/spark/SolrSupportScala.scala

Added SolrScalaRDD.scala and SolrSupportScala.scala. Upgraded to Spark 1.2

Scala Support and Spark 1.2 Upgrade

---

README.md
pom.xml
src/main/java/com/lucidworks/spark/ShardPartitioner.java
src/main/java/com/lucidworks/spark/SolrRDD.java
src/main/java/com/lucidworks/spark/SolrSupport.java
src/main/java/com/lucidworks/spark/example/hadoop/Logs2SolrRDDProcessor.java
src/main/java/com/lucidworks/spark/query/PagedResultsIterator.java
src/main/java/com/lucidworks/spark/util/EmbeddedSolrServerFactory.java
src/test/java/com/lucidworks/spark/TestSolrCloudClusterSupport.java

Initial upgrade for Solr 5.0. Still testing.

Created branch_5x for Solr 5.x

---

pom.xml
src/main/java/com/lucidworks/spark/example/query/ReadTermVectors.java

* I added few sections to fulfill the requirements of OSSRH guideline (http://central.sonatype.org/pages/apache-maven.html)
* The plugins javadoc, gpg are added to the release profile

Updated pom.xml for adding artifacts to OSSRH repository

---

src/main/java/com/lucidworks/spark/SchemaPreservingSolrRDD.java
src/main/java/com/lucidworks/spark/SolrRDD.java
src/main/java/com/lucidworks/spark/SolrRelation.java
src/main/java/com/lucidworks/spark/example/query/KMeansAnomaly.java
src/test/java/com/lucidworks/spark/SolrRelationTest.java

Tests are failing after merging this.

Revert "Metadata driven schema handling"

---

src/main/java/com/lucidworks/spark/query/SolrStreamIterator.java
src/main/scala/com/lucidworks/spark/SolrConf.scala
src/main/scala/com/lucidworks/spark/SolrRelation.scala
src/main/scala/com/lucidworks/spark/rdd/SolrRDD.scala
src/main/scala/com/lucidworks/spark/util/ConfigurationConstants.scala
src/main/scala/com/lucidworks/spark/util/SolrQuerySupport.scala
src/test/resources/conf/solrconfig.xml
src/test/resources/eventsim/fields_schema.json
src/test/scala/com/lucidworks/spark/EventsimTestSuite.scala
src/test/scala/com/lucidworks/spark/RDDTestSuite.scala

* Add a config option to make sql queries use the Solr export handler
TODO:
* Currently, the test I have added is failing. I am going to look into it soon.

Export handler support for Solr SQL

---

src/main/scala/com/lucidworks/spark/SolrRelation.scala
src/test/resources/test-data/simple.csv
src/test/scala/com/lucidworks/spark/TestQuerying.scala

The modifications I made to SolrRelation may be problematic for other reasons, but the test fails without them and succeeds with them.

SolrRelation can't handle varying column sets on read

---

docs/examples/twitter.adoc
pom.xml
src/main/java/com/lucidworks/spark/query/PagedResultsIterator.java
src/main/java/com/lucidworks/spark/query/StreamingResultsIterator.java
src/main/java/com/lucidworks/spark/util/EmbeddedSolrServerFactory.java
src/main/scala/com/lucidworks/spark/analysis/LuceneTextAnalyzer.scala
src/main/scala/com/lucidworks/spark/example/events/EventsimIndexer.scala
src/test/java/com/lucidworks/spark/RDDProcessorTestBase.java
src/test/java/com/lucidworks/spark/TestSolrCloudClusterSupport.java
src/test/java/com/lucidworks/spark/analysis/LuceneTextAnalyzerTest.java
src/test/java/com/lucidworks/spark/ml/feature/LuceneTextAnalyzerTransformerTest.java
src/test/resources/conf/solrconfig.xml
src/test/scala/com/lucidworks/spark/analysis/LuceneTextAnalyzerSuite.scala
src/test/scala/com/lucidworks/spark/ml/feature/LuceneTextAnalyzerTransformerSuite.scala

SPAR-27 Update to Solr 6.1 version

---

README.adoc

Update the Solr version link

---

src/main/scala/com/lucidworks/spark/util/SolrJsonSupport.scala
src/main/scala/com/lucidworks/spark/util/SolrSupport.scala

Fix spark-solr kerberos support

---

src/main/java/com/lucidworks/spark/query/HashQParserShardSplitStrategy.java
src/main/scala/com/lucidworks/spark/Partitioner.scala
src/main/scala/com/lucidworks/spark/SolrRelation.scala
src/main/scala/com/lucidworks/spark/rdd/SolrRDD.scala
src/main/scala/com/lucidworks/spark/util/SolrQuerySupport.scala
src/test/java/com/lucidworks/spark/SolrRelationTest.java
src/test/java/com/lucidworks/spark/SolrSqlTest.java
src/test/java/com/lucidworks/spark/util/EventsimUtil.java
src/test/resources/conf/lang/stopwords_en.txt
src/test/resources/conf/managed-schema
src/test/resources/conf/solrconfig.xml
src/test/scala/com/lucidworks/spark/EventsimTestSuite.scala
src/test/scala/com/lucidworks/spark/RelationTestSuite.scala
src/test/scala/com/lucidworks/spark/TestFramework.scala

* Isolate query object in the `buildScan` method

various bug fixes for 2.3.1 release

---

src/main/scala/com/lucidworks/spark/SolrConf.scala
src/main/scala/com/lucidworks/spark/SolrRelation.scala
src/main/scala/com/lucidworks/spark/util/ConfigurationConstants.scala
src/test/scala/com/lucidworks/spark/RelationTestSuite.scala

something like this:
```
val opts = Map("collection" -> "zipcodes", "exclude_fields" -> "id,_lw_*,*_\\d_coordinate")
var zipcodes = sqlContext.read.format("solr").options(opts).load
zipcodes.printSchema
```

support an exclude_fields option

---

src/main/scala/com/lucidworks/spark/util/SolrSupport.scala

Sometimes when a task takes too long to index documents, exceptions like this will be thrown out due to ZK session expiration
```
at org.apache.solr.common.cloud.ZkStateReader.getCollectionLive(ZkStateReader.java:1094)
at org.apache.solr.common.cloud.ZkStateReader$LazyCollectionRef.get(ZkStateReader.java:637)
at org.apache.solr.common.cloud.ClusterState.getCollectionOrNull(ClusterState.java:212)
at org.apache.solr.common.cloud.ClusterState.hasCollection(ClusterState.java:114)
at org.apache.solr.client.solrj.impl.CloudSolrClient.getCollectionNames(CloudSolrClient.java:1303)
at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:1025)
at org.apache.solr.client.solrj.impl.CloudSolrClient.request(CloudSolrClient.java:1004)
at …
```

Reset client cache if session expires

---

src/main/scala/com/lucidworks/spark/util/SolrRelationUtil.scala
src/test/scala/com/lucidworks/spark/RelationTestSuite.scala

long time bug here ... placement of wildcard in LIKE clause was in reverse

Fix placement of wildcard for handling LIKE clause

---

src/main/scala/com/lucidworks/spark/util/SolrRelationUtil.scala
src/test/scala/com/lucidworks/spark/RelationTestSuite.scala

Escape special characters in filter queries

---

src/main/java/com/lucidworks/spark/SparkSolrAccumulator.scala
src/main/java/com/lucidworks/spark/query/ResultsIterator.java
src/main/java/com/lucidworks/spark/query/StreamingResultsIterator.java
src/main/java/com/lucidworks/spark/query/TupleStreamIterator.java
src/main/scala/com/lucidworks/spark/SolrConf.scala
src/main/scala/com/lucidworks/spark/SolrRelation.scala
src/main/scala/com/lucidworks/spark/rdd/SelectSolrRDD.scala
src/main/scala/com/lucidworks/spark/rdd/SolrRDD.scala
src/main/scala/com/lucidworks/spark/rdd/StreamingSolrRDD.scala
src/main/scala/com/lucidworks/spark/util/ConfigurationConstants.scala
src/main/scala/com/lucidworks/spark/util/SolrSupport.scala
src/main/scala/org/apache/spark/solr/SparkInternalObjects.scala
src/test/scala/com/lucidworks/spark/EventsimTestSuite.scala

Add accumulators for read and write operations

---

README.adoc
pom.xml
src/main/java/com/lucidworks/spark/SparkApp.java
src/main/java/com/lucidworks/spark/fusion/FusionPipelineClient.java
src/main/scala/com/lucidworks/spark/analysis/LuceneTextAnalyzer.scala
src/main/scala/com/lucidworks/spark/example/NewRDDExample.scala
src/main/scala/com/lucidworks/spark/example/RDDExample.scala
src/main/scala/com/lucidworks/spark/example/query/QueryBenchmark.scala
src/main/scala/com/lucidworks/spark/util/SolrRelationUtil.scala
src/main/scala/com/lucidworks/spark/util/SolrSupport.scala
src/test/java/com/lucidworks/spark/TestSolrCloudClusterSupport.java
src/test/java/com/lucidworks/spark/analysis/LuceneTextAnalyzerTest.java
src/test/java/com/lucidworks/spark/ml/feature/LuceneTextAnalyzerTransformerTest.java
src/test/scala/com/lucidworks/spark/EventsimTestSuite.scala
src/test/scala/com/lucidworks/spark/TestFramework.scala
src/test/scala/com/lucidworks/spark/analysis/LuceneTextAnalyzerSuite.scala
src/test/scala/com/lucidworks/spark/ml/feature/LuceneTextAnalyzerTransformerSuite.scala
src/test/scala/com/lucidworks/spark/util/SolrCloudUtil.scala

* Codehale conflicts with Spark and Solr are resolved. Codehale metrics from Spark should be excluded wherever Solr is involved.

Upgrade to Solr 7.0.0

---

src/main/scala/com/lucidworks/spark/SolrRelation.scala

Basically, just moved some of the schema field mgmt code to the SolrRelation object.

Minor refactoring to simplify doing partial updates 

---

src/main/java/com/lucidworks/spark/fusion/FusionPipelineClient.java

Added a couple more utility methods to FPC to make it easier to use from Scala, e.g.:
```
def queryFusion(fusion: FusionPipelineClient, queryParams: Map[String,String]) : Option[JsonNode] = {
try {
val jsonTree = fusion.queryFusion(queryProfilePath, queryParams.asJava)
if (jsonTree != null) {
val response = jsonTree.get("response")
if (response != null) {
val docs = response.get("docs")
if (docs.isArray && docs.size > 0) {
return Some(jsonTree)
}
}
}
} catch {
case exc : Exception => log.info(s"Query [${queryParams.mkString("&")}] failed due to: ${exc}")
case thr : Throwable => throw thr
}
return None
}
```
and for indexing:
```
def postSignal(fusion: FusionPipelineClient, signalDoc: Map[String,_]) = {
val timestamp = DateTimeFormatter.ISO_INSTANT.format((new Date()).toInstant)
val withTs …
```

Add queryFusion method to FPC

---

src/main/java/com/lucidworks/spark/fusion/FusionPipelineClient.java

Use headers to send requests to fusion using trusted realm

Work with a Fusion trusted realm

---

pom.xml
src/main/java/com/lucidworks/spark/util/EmbeddedSolrServerFactory.java
src/main/resources/embedded/solr.xml
src/main/resources/embedded/solrconfig.xml
src/test/java/com/lucidworks/spark/solr/TestEmbeddedSolrServer.java
src/test/resources/conf/managed-schema
src/test/resources/custom-solrconfig.xml

* Add a method for user to pass in custom solr config or custom solr.xml
* Add unit tests

EmbeddedSolrServerFactory improvements  and tests

---

src/main/scala/com/lucidworks/spark/TimePartitioningQuery.scala
src/test/scala/com/lucidworks/spark/TestPartitionByTimeQuerySupport.scala

Rebased against master now. Previous PR #258

APOLLO-18555 Add monthly timeslice support

---

src/main/scala/com/lucidworks/spark/util/SolrRelationUtil.scala
src/test/java/com/lucidworks/spark/SolrRelationTest.java

Changes the behavior of multi-value fields

APOLLO-17872 Predicates on multi-valued fields are broken

---

pom.xml
src/test/scala/com/lucidworks/spark/TestQuerying.scala

Reverts lucidworks/spark-solr#260

Revert "Upgrade spark and solr"

---

src/main/scala/com/lucidworks/spark/util/SolrRelationUtil.scala
src/test/scala/com/lucidworks/spark/MovieLensTestSuite.scala
src/test/scala/com/lucidworks/spark/TestFramework.scala

* NOT operator is not supported inside AND or OR clauses. This PR adds that

Add support for NOT operator inside nested clauses

---

pom.xml
src/test/scala/com/lucidworks/spark/TestQuerying.scala

* Spark upgraded to 2.4.4
* Solr upgraded to 8.3.0

Upgrade Spark and Solr

---

src/main/scala/com/lucidworks/spark/util/SolrQuerySupport.scala
src/test/scala/com/lucidworks/spark/RelationTestSuite.scala

* The current impl is not tail recursive which will cause stack overflow errors. Change the recursion to tail recursion and do better asserts in tests

Make field fetching tail recursive

---

README.adoc
pom.xml

Updates to build against Spark 2.4.5

Update to Spark 2.4.5

---

pom.xml
src/main/java/com/lucidworks/spark/util/EmbeddedSolrServerFactory.java
src/test/java/com/lucidworks/spark/TestSolrCloudClusterSupport.java
src/test/resources/conf/solrconfig.xml
src/test/resources/custom-solrconfig.xml
src/test/scala/com/lucidworks/spark/TestFramework.scala
src/test/scala/com/lucidworks/spark/TestQuerying.scala

(presumes the #312 changes make sense and happen first or are included here)
links related to the code changes:
* https://issues.apache.org/jira/browse/SOLR-14659 and https://github.com/apache/lucene-solr/pull/1960
* https://issues.apache.org/jira/browse/SOLR-14197 and https://github.com/apache/lucene-solr/commit/17ae79b0905b2bf8635c1b260b30807cae2f5463#diff-b55d06ed2f9b3b541be083c5bb4fc09ddf0017f55938c9091bc558ed2e48cc02

upgrade to Apache Solr 8.8.2

---

pom.xml
src/test/scala/com/lucidworks/spark/TestQuerying.scala

follow-up after or alternative to #334 upgrade to 8.10.1

upgrade to Apache Solr 8.11.0
