- README.adoc
This pull request changes the README from Markdown format to Asciidoc format for more advanced styling and content re-use via tagged content areas.
> Convert README.md to README.adoc

- pom.xml
Update pom.xml to include a licenses section, with the Apache License Version 2.0 per the LICENSE file.
This allows tools like https://github.com/hierynomus/license-gradle-plugin to gather license information automatically.
The content and example comes from https://maven.apache.org/pom.html#Licenses
The position in the XML file is per http://maven.apache.org/xsd/maven-4.0.0.xsd
> Update pom.xml to include a licenses section

- src/main/java/com/lucidworks/spark/SolrRelation.java
- src/test/java/com/lucidworks/spark/SolrRelationTest.java
https://github.com/LucidWorks/spark-solr/issues/20
Simply I added a missing filter which is added for Spark 1.5 and tested passing all the testcodes including one I added.
Spark does not pass `EqualNullSafe` filter having null value but instead `IsNull`. So it is safe to process identically with `EqualTo`.
> Support for null-safe equality comparison (added from Spark 1.5).

- src/main/java/com/lucidworks/spark/SchemaPreservingSolrRDD.java
- src/main/java/com/lucidworks/spark/SolrRDD.java
- src/main/java/com/lucidworks/spark/SolrRelation.java
- src/main/java/com/lucidworks/spark/example/query/KMeansAnomaly.java
- src/test/java/com/lucidworks/spark/SolrRelationTest.java
My use case for solr is more focused on docValues than stored fields to reduce the fieldCache as much as possible. I also use a mongo _id as the uniqueKey instead of the default field that we instead use just for shard routing since solr is just our index overlay for our primary mongo data store and not being treated as a standalone read/write data store.  I'm planning in a separate branch to include support for the export handler so that the multiValued docValues fields can be accessible (also due to my use case) but I'm not sure if I have to switch to solr.io streaming and therefore require solr 5.x instead of being backwards compatible to 4.10.4  or if I can hack something using the SolrJsonSupport.getJson.
> Metadata driven schema handling

- src/main/java/com/lucidworks/spark/SchemaPreservingSolrRDD.java
- src/main/java/com/lucidworks/spark/SolrRDD.java
- src/main/java/com/lucidworks/spark/SolrRelation.java
- src/main/java/com/lucidworks/spark/example/query/KMeansAnomaly.java
- src/test/java/com/lucidworks/spark/SolrRelationTest.java
@thelabdude The nested tests have been fixed in this refactor with more aggressive checks against the internal fieldList length in the getQuerySchema call and applyFields calls
> Schema driven unique key with field escaping and docValues support

- src/main/java/com/lucidworks/spark/query/AbstractFieldShardSplitStrategy.java
- src/main/java/com/lucidworks/spark/query/NumberFieldShardSplitStrategy.java
- src/test/java/com/lucidworks/spark/query/ShardSplitStrategyTest.java
* Changed the split strategy to produce zero splits if there are no docs (instead of throwing the exception). This will prevent the spark job from failing if there are no docs.
* Added a unit test "testSplitStrategyEmptyCollection"
> Return zero splits instead of throwing an exception if there are on docs

- src/main/scala/com/lucidworks/spark/rdd/SolrRDD.scala
- src/main/scala/com/lucidworks/spark/util/SolrRelationUtil.scala
- src/test/java/com/lucidworks/spark/SolrRelationTest.java
- src/test/java/com/lucidworks/spark/SolrSqlTest.java
- src/test/java/com/lucidworks/spark/util/EventsimUtil.java
- src/test/scala/com/lucidworks/spark/EventsimTestSuite.scala
Fixes #40 which is to able to filter SQL queries using timestamp fields.
>  Support for timestamp filters from Spark SQL

- src/main/scala/com/lucidworks/spark/util/SolrQuerySupport.scala
- src/main/scala/com/lucidworks/spark/util/SolrRelationUtil.scala
- src/test/java/com/lucidworks/spark/SolrRelationTest.java
- src/test/java/com/lucidworks/spark/SolrSqlTest.java
- src/test/resources/eventsim/fields_schema.json
- src/test/scala/com/lucidworks/spark/EventsimTestSuite.scala
* Streaming Expressions already do this. They implicitly do the casting. See https://lucene.apache.org/solr/5_3_0/solr-solrj/org/apache/solr/client/solrj/io/Tuple.html
* We are doing this to have consistency between both Streaming and non streaming approaches
> Convert Integer to Long and Float to Double

- src/main/java/com/lucidworks/spark/query/StreamingResultsIterator.java
- src/main/scala/com/lucidworks/spark/SolrConf.scala
- src/main/scala/com/lucidworks/spark/SolrRelation.scala
- src/main/scala/com/lucidworks/spark/util/ConfigurationConstants.scala
- src/test/java/com/lucidworks/spark/SolrRelationTest.java
- src/test/resources/conf/managed-schema
allow users to read a random sample from all shards instead of the full dataset
> Random sample support

- src/main/java/com/lucidworks/spark/query/SolrStreamIterator.java
- src/main/scala/com/lucidworks/spark/SolrConf.scala
- src/main/scala/com/lucidworks/spark/SolrRelation.scala
- src/main/scala/com/lucidworks/spark/rdd/SolrRDD.scala
- src/main/scala/com/lucidworks/spark/util/ConfigurationConstants.scala
- src/test/scala/com/lucidworks/spark/EventsimTestSuite.scala
* Automatically use export handler if the query fields and sort field have docValues enabled
> Use export handler for querying by default (if possible)

- src/main/scala/com/lucidworks/spark/SolrRelation.scala
- src/main/scala/com/lucidworks/spark/rdd/SolrRDD.scala
- src/main/scala/com/lucidworks/spark/util/SolrSupport.scala
- src/main/scala/solr/DefaultSource.scala
- src/test/scala/com/lucidworks/spark/TestQuerying.scala
The test has been added to TestQuerying.scala. The collections that we are querying to must have the same schema
> Spar 29: Adding support for querying multiple collections

- pom.xml
Otherwise using scala 2.11 leads to "interesting" failures at runtime.
> use ${scala.binary.version} in jackson dependency

- src/main/java/com/lucidworks/spark/query/AbstractFieldShardSplitStrategy.java
This happens when the number of hits is less than the number of splits per shard.
> Prevent divide by zero

- src/main/scala/com/lucidworks/spark/rdd/SolrRDD.scala
- src/main/scala/com/lucidworks/spark/util/SolrQuerySupport.scala
- src/test/java/com/lucidworks/spark/RDDProcessorTestBase.java
* If the index is actively written to while the query is happening, the queries that use cursorMarks will fail. This PR restricts the query to the current index (as of query time) by adding filter queries on `_version_`. There is a slight overhead to this due to the 2 queries happening to determine the `_version_` min, max
> Freeze the index using filter queries before querying any shards

- src/main/scala/com/lucidworks/spark/SolrConf.scala
- src/main/scala/com/lucidworks/spark/SolrRelation.scala
- src/main/scala/com/lucidworks/spark/util/ConfigurationConstants.scala
- src/main/scala/com/lucidworks/spark/util/SolrQuerySupport.scala
- src/main/scala/com/lucidworks/spark/util/SolrRelationUtil.scala
- src/test/java/com/lucidworks/spark/query/StreamingResultsIteratorTest.java
- src/test/scala/com/lucidworks/spark/RelationTestSuite.scala
Example:
```
val opts = Map("zkhost" -> zkHost, "collection" -> moviesCollection, skip_non_dv -> "true")
sqlContext.read.format("solr").options(opts).load()
```
The following code removes all the fields that do not have docValues from the schema
> Add option to skip non docValue fields

- src/main/scala/com/lucidworks/spark/SolrRelation.scala
- src/main/scala/com/lucidworks/spark/util/SolrQuerySupport.scala
- src/main/scala/com/lucidworks/spark/util/SolrRelationUtil.scala
* If a lot of dynamic fields exist in the Luke handler, do multiple requests to get the schema information for all those fields. (Previously, we didn't support schema for dynamic fields if the url size exceeded 2048)
* Schema should only have fields that are populated in the Luke handler
> Do multiple requests to get schema of the dynamic fields

- README.adoc
Listed all the releases that are on maven central. I have only marked the most recent version of a release 
@thelabdude this is how it would look like https://github.com/lucidworks/spark-solr/blob/0cb523d6d0cf919836a2dac78981b2db107f1229/README.adoc#version-compatibility
> SPAR-35 Compatibility version matrix

- src/main/scala/com/lucidworks/spark/SolrConf.scala
- src/main/scala/com/lucidworks/spark/SolrRelation.scala
- src/main/scala/com/lucidworks/spark/SolrSQLHiveContext.scala
- src/main/scala/com/lucidworks/spark/util/ConfigurationConstants.scala
- src/test/scala/com/lucidworks/spark/MovieLensTestSuite.scala
* 'score' field in 'sql' statement will be considered as a double 
* Config property `sql_schema` can be used to specify custom schema for Solr SQL statements
> SPAR-43 Treat 'score' field as a special property and custom sql schema

- src/main/java/com/lucidworks/spark/query/SolrStreamIterator.java
Take advantage of SOLR-9721. Improves the performance of `/export` handler
> Use Javabin for SolrStream iterator

- src/main/java/com/lucidworks/spark/query/ResultsIterator.java
- src/main/java/com/lucidworks/spark/query/StreamingExpressionResultIterator.java
- src/main/java/com/lucidworks/spark/query/StreamingResultsIterator.java
- src/main/java/com/lucidworks/spark/query/TupleStreamIterator.java
- src/main/java/com/lucidworks/spark/rdd/SolrJavaRDD.java
- src/main/java/com/lucidworks/spark/rdd/SolrStreamJavaRDD.java
- src/main/scala/com/lucidworks/spark/SolrConf.scala
- src/main/scala/com/lucidworks/spark/SolrRelation.scala
- src/main/scala/com/lucidworks/spark/example/NewRDDExample.scala
- src/main/scala/com/lucidworks/spark/example/RDDExample.scala
- src/main/scala/com/lucidworks/spark/example/query/QueryBenchmark.scala
- src/main/scala/com/lucidworks/spark/example/query/WordCount.scala
- src/main/scala/com/lucidworks/spark/rdd/SelectSolrRDD.scala
- src/main/scala/com/lucidworks/spark/rdd/SolrRDD.scala
- src/main/scala/com/lucidworks/spark/rdd/StreamingSolrRDD.scala
- src/main/scala/com/lucidworks/spark/util/ConfigurationConstants.scala
- src/main/scala/com/lucidworks/spark/util/Constants.scala
- src/main/scala/com/lucidworks/spark/util/SolrQuerySupport.scala
- src/main/scala/com/lucidworks/spark/util/SolrRelationUtil.scala
- src/test/java/com/lucidworks/spark/RDDProcessorTestBase.java
- src/test/java/com/lucidworks/spark/SolrRDDTest.java
- src/test/scala/com/lucidworks/spark/EventsimTestSuite.scala
- src/test/scala/com/lucidworks/spark/RDDTestSuite.scala
* SolrRDD is an abstract parameterized class and SelectSolrRDD, StreamingSolrRDD extend SolrRDD
* StreamingSolrRDD should be used for `/export`, `/stream`, `/sql`
* SelectSolrRDD should be used for everything else
* Return RDD[Map] for streaming expressions
* Avoid conversion of Tuple to SolrDocument during the fetching in stages
* Handling SOLR-9732 at Row conversion time. [commit](https://github.com/lucidworks/spark-solr/pull/132/commits/8c62bd4d5a16640ed73612d776cc766d8f4b10e4)
* Breaking compatibility with SolrJavaRDD. `SolrJavaRDD.get()` returns `SelectSolrRDD`
> SPAR-42 Parameterize SolrRDD and avoid conversions between Tuple and SolrDocument

- src/main/scala/com/lucidworks/spark/SolrRelation.scala
- src/test/scala/com/lucidworks/spark/EventsimTestSuite.scala
- src/test/scala/com/lucidworks/spark/TestSolrRelation.scala
* This should make the class unit testable without requiring a running Solr
> Lazy initialize SolrRelation variables

- src/main/java/com/lucidworks/spark/fusion/FusionPipelineClient.java
- src/main/scala/com/lucidworks/spark/SolrRelation.scala
- src/main/scala/com/lucidworks/spark/rdd/StreamingSolrRDD.scala
- src/test/scala/com/lucidworks/spark/RelationTestSuite.scala
Make sure the schema used for building rows from a streaming expression matches the projected fields passed into buildScan
> Fix projection of push-down fields if supplied for streaming expr

- README.adoc
- src/main/scala/com/lucidworks/spark/util/SolrJsonSupport.scala
- src/main/scala/com/lucidworks/spark/util/SolrSupport.scala
* via system property 'basicauth' or 'solr.httpclient.config'
* The username/password can be passed via `bascicauth` in the form of `-Dbasicauth=solr:SolrRocks`
* Passed in via config file `-Dsolr.httpclient.config=/Users/kiran/spark/spark-2.1.0-bin-hadoop2.7/auth.txt`
These properties have to be set on driver JVM and all the executor JVMs
Example: (**basicauth**) 
```
./bin/spark-shell --master local[*] --jars ~/Git/spark-solr/target/spark-solr-3.0.1-SNAPSHOT-shaded.jar  --conf 'spark.driver.extraJavaOptions=-Dbasicauth=solr:SolrRocks'
```
Example: (**solr.httpclient.config**)
```
./bin/spark-shell --master local[*] --jars ~/Git/spark-solr/target/spark-solr-3.0.1-SNAPSHOT-shaded.jar  --conf 'spark.driver.extraJavaOptions=-Dsolr.httpclient.config=/Users/kiran/spark/spark-2.1.0-bin-hadoop2. …
```
> Support Basic auth for Solr

- src/main/scala/com/lucidworks/spark/rdd/SelectSolrRDD.scala
- src/main/scala/com/lucidworks/spark/rdd/StreamingSolrRDD.scala
- src/main/scala/com/lucidworks/spark/util/SolrSupport.scala
* Support system params for defining config files for basic auth and kerberos
* Configs are `kerberos.config`, `basicauth.config`
* When these params are defined, the files defined in the configs are loaded using `SparkFiles` and then the appropriate system param is defined with the absolute path
> Support config options for basic auth and kerberos

- src/main/scala/com/lucidworks/spark/util/SolrDataFrameImplicits.scala
- src/test/scala/com/lucidworks/spark/EventsimTestSuite.scala
- src/test/scala/com/lucidworks/spark/TestIndexing.scala
to add "df.write.solr(collection)" and "sparkSession.read.solr(collection, readQuery)" functionality
> DataFrame reader/writer implicits,

- src/main/scala/com/lucidworks/spark/Partitioner.scala
- src/main/scala/com/lucidworks/spark/rdd/SolrRDD.scala
Current implementation will give `replicaHostName`, such as `idx5.oi.dev:8983_solr`, to the Spark. Which will cause the `parseInt` method in Spark YarnScheduer get the `java.lang.NumberFormatException`, since `8983_solr` is not integer. Bellow is a error log
```
17/06/21 12:40:53 INFO ContextLauncher: 17/06/21 12:40:53 ERROR scheduler.DAGSchedulerEventProcessLoop: DAGSchedulerEventProcessLoop failed; shutting down SparkContext
17/06/21 12:40:53 INFO ContextLauncher: java.lang.NumberFormatException: For input string: “8983_solr”
17/06/21 12:40:53 INFO ContextLauncher: 	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
17/06/21 12:40:53 INFO ContextLauncher: 	at java.lang.Integer.parseInt(Integer.java:580)
17/06/21 12:40:53 INFO ContextLauncher: 	at …
```
> Make spark get the right host&port without the tailing '_solr'.

- src/main/scala/com/lucidworks/spark/Partitioner.scala
- src/main/scala/com/lucidworks/spark/SolrRDDPartition.scala
- src/main/scala/com/lucidworks/spark/rdd/SelectSolrRDD.scala
- src/main/scala/com/lucidworks/spark/rdd/SolrRDD.scala
- src/main/scala/com/lucidworks/spark/rdd/StreamingSolrRDD.scala
- src/main/scala/com/lucidworks/spark/util/SolrQuerySupport.scala
- src/test/scala/com/lucidworks/spark/RelationTestSuite.scala
- src/test/scala/com/lucidworks/spark/TestShardSplits.scala
* Works only for `/select` handler
* When the task fails once, we check the health of the replica and switch to another replica if the preferredReplica can't be queried
> Replica fallback if the replica goes down during task compute

- src/main/scala/com/lucidworks/spark/rdd/StreamingSolrRDD.scala
- src/main/scala/com/lucidworks/spark/util/SolrQuerySupport.scala
- src/main/scala/com/lucidworks/spark/util/SolrSupport.scala
- src/test/scala/com/lucidworks/spark/RelationTestSuite.scala
* Luke handler in SolrCloud is not cloud aware
* Hence, we have to request data from each shard and combine it all. Otherwise, the code will fail if docs are not evenly distributed between shards
* Wrote a test that would fail (2 out of 10 times without the fix)
> Get luke fields response from all shards

- pom.xml
- src/main/scala/com/lucidworks/spark/SolrRelation.scala
- src/main/scala/com/lucidworks/spark/util/SolrSupport.scala
- src/test/resources/conf/managed-schema
- src/test/scala/com/lucidworks/spark/TestQuerying.scala
* "movielens data analytics" in RelationTestSuite is failing if rating is a `pint` field. As a workaround, I defined it as a `tint` field for now
> Define fields (during indexing) based on solr version

- src/main/scala/com/lucidworks/spark/TimePartitioningQuery.scala
- src/test/scala/com/lucidworks/spark/TestPartitionByTimeQuerySupport.scala
* Optimize SQL timestamp queries like
```
select * from events where timestamp  > 2017-11-20 and timestamp < 2017-11-22
```
* Previously, the above query would return a list like [2017-11-20, 2017-11-21, 2017-11-22, 2017-11-23, 2017-11-24, ...]
* With this PR, the list will subset to [2017-11-20, 2017-11-21]
> Multiple range queries timestamp

- pom.xml
We attempted to integrate Solr into Spark on the Databricks environment.  This was complicated by a couple of library conflicts.  In particular, Scala Logging and the Apache HTTP Client had a different version.  Our workaround is a local, forked build of the project.  This PR attempts to merge our fork back into upstream.
Here are a couple of errors we ran into - might be useful for others to find this.  First, we ran into the issue of not being able to resolve `org.restlet.jee:org.restlet:2.3.0, org.restlet.jee:org.restlet.ext.servlet:2.3.0`.
Databricks uses `/databricks/jars/spark--maven-trees--spark_2.2--com.typesafe.scala-logging--scala-logging-slf4j_2.11--com.typesafe.scala-logging__scala-logging-slf4j_2.11__2.1.2.jar` and the Solr package uses …
> Enable Databricks Integration

- pom.xml
- src/main/scala/com/lucidworks/spark/SolrConf.scala
- src/main/scala/com/lucidworks/spark/SolrRelation.scala
- src/main/scala/com/lucidworks/spark/util/ConfigurationConstants.scala
- src/main/scala/com/lucidworks/spark/util/SolrRelationUtil.scala
- src/test/java/com/lucidworks/spark/RDDProcessorTestBase.java
- src/test/resources/test-data/simple.csv
- src/test/scala/com/lucidworks/spark/EventsimTestSuite.scala
- src/test/scala/com/lucidworks/spark/TestFramework.scala
- src/test/scala/com/lucidworks/spark/TestIndexing.scala
- src/test/scala/com/lucidworks/spark/TestSolrRelation.scala
* Upgrade to Spark 2.3.1
* Fix nested filters in SQL
* Provide option for user to specify field type for fields while indexing
> Spark upgrade to 2.3.1 and bug fixes

- pom.xml
- src/main/java/com/lucidworks/spark/query/SparkSolrClientCache.java
- src/main/java/com/lucidworks/spark/query/StreamingExpressionResultIterator.java
- src/main/scala/com/lucidworks/spark/JsonFacetUtil.scala
- src/main/scala/com/lucidworks/spark/Logging.scala
- src/main/scala/com/lucidworks/spark/SolrConf.scala
- src/main/scala/com/lucidworks/spark/SolrRelation.scala
- src/main/scala/com/lucidworks/spark/TimePartitioningQuery.scala
- src/main/scala/com/lucidworks/spark/example/NewRDDExample.scala
- src/main/scala/com/lucidworks/spark/example/RDDExample.scala
- src/main/scala/com/lucidworks/spark/example/ml/NewsgroupsIndexer.scala
- src/main/scala/com/lucidworks/spark/ml/feature/LuceneTextAnalyzerTransformer.scala
- src/main/scala/com/lucidworks/spark/rdd/SelectSolrRDD.scala
- src/main/scala/com/lucidworks/spark/rdd/SolrRDD.scala
- src/main/scala/com/lucidworks/spark/rdd/StreamingSolrRDD.scala
- src/main/scala/com/lucidworks/spark/util/SolrQuerySupport.scala
- src/main/scala/com/lucidworks/spark/util/SolrRelationUtil.scala
- src/main/scala/com/lucidworks/spark/util/SolrSupport.scala
- src/test/scala/com/lucidworks/spark/RDDTestSuite.scala
- src/test/scala/com/lucidworks/spark/RelationTestSuite.scala
- src/test/scala/com/lucidworks/spark/SparkSolrFunSuite.scala
- src/test/scala/com/lucidworks/spark/TestFramework.scala
- src/test/scala/com/lucidworks/spark/util/SolrCloudUtil.scala
* typesafe dependency inside spark-solr has caused us problems with dep conflicts
* Last release of spark-solr doesn't play fine with stock Spark due to typesafe dependency conflicts
* This PR removes typesafe dependency and introduces our own logger similar to typesafe logger
> Remove typesafe dependency for logging

- src/main/scala/com/lucidworks/spark/SolrConf.scala
- src/main/scala/com/lucidworks/spark/SolrRelation.scala
- src/main/scala/com/lucidworks/spark/util/ConfigurationConstants.scala
- src/main/scala/com/lucidworks/spark/util/SolrRelationUtil.scala
- src/test/scala/com/lucidworks/spark/EventsimTestSuite.scala
* Skip luke call if user has explicitly requested for fields using `fields` config param
* Skip luke and schema call if user explicitly sets the schema using `schema` config param
* Luke is a very expensive call (especially since it hits each shard) for SQL type queries
> Skip luke calls if schema is defined

- src/main/scala/com/lucidworks/spark/util/SolrQuerySupport.scala
By default, /luke fetches index flags for all fields it returns.  This
can be expensive when shards have a large number of fields.  We only
use /luke to fetch the field-names, so this commit adds the
'includeIndexFieldFlags=false' flag to our /luke calls so they avoid
this slowdown.
> APOLLO-18556: Don't fetch index flags from /luke

- pom.xml
- src/test/scala/com/lucidworks/spark/TestQuerying.scala
Upgrade
*  Spark to 2.4.3
*  Solr to 7.7.1
*  Scala to 2.11.12
* Junit to 4.12
I tried upgrading to Solr 8.1 but it seems to be a more involved effort that needs to be evaluated. We should do that as a separate PR
> Upgrade spark and solr

- pom.xml
- src/test/scala/com/lucidworks/spark/TestQuerying.scala
Brings in latest Solr version.  Solr depends on ZooKeeper 3.5.5 now, so
this changes our effective ZooKeeper and Curator versions as well.
> APOLLO-20848: Upgrade Solr to 8.2.0

- pom.xml
New version of gpg requires these arguments for pulling the passphrase from the settings.xml file
> APOLLO-22156-added-gpg-arguments

- src/main/scala/com/lucidworks/spark/SolrConf.scala
- src/main/scala/com/lucidworks/spark/SolrRelation.scala
- src/main/scala/com/lucidworks/spark/SolrStreamWriter.scala
- src/main/scala/com/lucidworks/spark/analysis/LuceneTextAnalyzer.scala
- src/main/scala/solr/DefaultSource.scala
- src/test/resources/log4j.properties
- src/test/scala/com/lucidworks/spark/TestIndexing.scala
- src/test/scala/com/lucidworks/spark/TestSolrStreamWriter.scala
* Users can now stream data to Solr from any Spark supported datasource
* In order to preserve exactly once semantics, users should set `id` (primary field) field before streaming the data out to Solr
> Add Spark streaming

- pom.xml
Reverts lucidworks/spark-solr#286
Build failing to resolve deps
```
Caused by: org.sonatype.aether.transfer.ArtifactTransferException: Could not transfer artifact org.restlet.jee:org.restlet:pom:2.3.0 from/to Restlet Releases (https://maven.restlet.com/): Received fatal alert: handshake_failure
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:951)
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$4.wrap(WagonRepositoryConnector.java:941)
at org.sonatype.aether.connector.wagon.WagonRepositoryConnector$GetTask.run(WagonRepositoryConnector.java:669)
at org.sonatype.aether.util.concurrency.RunnableErrorForwarder$1.run(RunnableErrorForwarder.java:60)
... 3 more
Caused by: org.apache.maven.wagon.TransferFailedException: Received …
```
> Revert "[SECURITY] Use HTTPS to resolve dependencies in Maven Build"

- src/main/java/com/lucidworks/spark/fusion/FusionPipelineClient.java
- src/main/scala/com/lucidworks/spark/util/SolrSupport.scala
Changed the httpclient 3.1 class imports to httpclient 4.x class imports. This
would affect anyone trying to exclude spark-solr's hadoop dependencies and include
newer hadoop dependencies for other purposes. This didn't seem to break anything -- the 
tests passed, the project compiled, and our spark jobs worked! -- but we don't utilize any of 
the hadoop/hdfs features of the spark-solr connector. However, this PR should be harmless.
Reference issue here: lucidworks/spark-solr#272
> changed httpclient 3.1 class imports to httpclient 4.x equivalent classes

- src/test/java/com/lucidworks/spark/TestSolrCloudClusterSupport.java
The `CloudSolrClient.Builder()` and `CloudSolrClient.Builder.withZkHost(String)` APIs are deprecated as per the https://solr.apache.org/docs/8_4_1/solr-solrj/org/apache/solr/client/solrj/impl/CloudSolrClient.Builder.html documentation.
> replace deprecated API use in TestSolrCloudClusterSupport

- src/main/java/com/lucidworks/spark/example/ml/MLPipeline.java
- src/main/java/com/lucidworks/spark/example/query/KMeansAnomaly.java
- src/main/scala/com/lucidworks/spark/example/ml/MLPipelineScala.scala
- src/test/java/com/lucidworks/spark/SolrRelationTest.java
- src/test/java/com/lucidworks/spark/SolrSqlTest.java
- src/test/java/com/lucidworks/spark/util/EventsimUtil.java
javadoc links:
* http://spark.apache.org/docs/2.4.5/api/java/org/apache/spark/sql/Dataset.html#registerTempTable-java.lang.String-
* http://spark.apache.org/docs/2.4.5/api/java/org/apache/spark/mllib/evaluation/MulticlassMetrics.html#fMeasure--
> replace deprecated org.apache.spark API use (in examples and tests)

- pom.xml
- src/test/resources/conf/solrconfig.xml
- src/test/resources/custom-solrconfig.xml
When running the tests locally I noticed warnings in the output e.g.
```
WARN  FieldTypePluginLoader  - TokenizerFactory is using deprecated 6.4.2 emulation. You should at some point declare and reindex to at least 7.0, because 6.x emulation is deprecated and will be removed in 8.0
```
* Increasing the tests' `luceneMatchVersion` version removes the warnings but I don't know if the versions currently in use are used for a specific reason or not?
* The `spark-solr/src/main/resources/embedded/solrconfig.xml` file e.g. https://github.com/lucidworks/spark-solr/blob/v3.7.6/src/main/resources/embedded/solrconfig.xml#L3 uses `<luceneMatchVersion>LATEST</luceneMatchVersion>` and if no specific version is intended or required for the tests then using `LATEST` could be an alternative too.
* edit: …
> use LATEST luceneMatchVersion in test/resources

- src/main/java/com/lucidworks/spark/query/TupleStreamIterator.java
javadoc link: https://solr.apache.org/docs/8_8_2/solr-solrj/org/apache/solr/client/solrj/io/Tuple.html#getMap--
> replace deprecated org.apache.solr.client.solrj.io.Tuple.getMap() API use

- src/main/resources/embedded/solr.xml
- src/test/resources/solr.xml
This pull request proposes to change the Solr metrics collection default from `true` to `false` and to provide an option to override via `-DmetricsEnabled=true` on the command line.
* for the spark-solr use case Solr metrics collection and metrics use may (and I'm speculating here) not be as common or useful as for a solr Solr use case
* metrics collection can be disabled as documented at https://solr.apache.org/guide/8_8/metrics-reporting.html#disabling-the-metrics-collection
* if metrics collection is disabled then as per https://github.com/apache/lucene-solr/blob/releases/lucene-solr/8.8.2/solr/core/src/java/org/apache/solr/core/CoreContainer.java#L752-L756 code snippet no `MetricsCollectorHandler` object is created
* from Apache Solr 8.9.0 onwards the `MetricsCollectorHandler` class …
> change Solr metrics collection default (from true to false)

- README.adoc
- src/main/scala/com/lucidworks/spark/SolrConf.scala
- src/main/scala/com/lucidworks/spark/SolrRelation.scala
- src/main/scala/com/lucidworks/spark/rdd/StreamingSolrRDD.scala
- src/test/scala/com/lucidworks/spark/EventsimTestSuite.scala
There are two small changes in Spark-Solr that will have a big impact on performance and usability. 
1. Set the default splits_per_shard to 1. By default if splits_per_shard is not set spark-solr uses a formula to compute splits_per_shard which can create a huge number of splits which will grind the cluster to a halt. Having the default behavior result in a trap is very detrimental to usability. It's very difficult for the typical user to understand the effect of splits_per_shard so the safest approach is to simply default to 1. Users can experiment with increasing this number to see if it improves performance or causes problems.
2. Change the default export handler sort field from id to `_version_ `. Spark does not utilize the sort order anyway so spark-solr should simply sort on the …
> FUS-3017: Spark-Solr performance improvements
